// WENO-Z reconstruction on Legendre polynomial basis with Zhang-Shu positivity limiter.

#include "aderweno/weno.hpp"
#include "aderweno/checks.hpp"
#include "aderweno/constants.hpp"

#include <cmath>
#include <algorithm>
#include <vector>

// ====================================================================
//  WENO-Z reconstruction (Castro, Costa, Don, JCP 2011)
//
//  Framework: Dumbser et al. (JCP 2008) Legendre polynomial basis
//  Weights:   WENO-Z (Castro et al. 2011)
//
//  - Always 3 fixed stencils: left-shifted, central, right-shifted
//  - Reconstruction in Legendre polynomial basis on [0,1]
//  - Oscillation indicator: sigma = R_{lm} * w_l * w_m  (matrix form)
//  - Optimal linear weights: d_C = 2/3, d_L = d_R = 1/6  (sum to 1)
//  - WENO-Z: alpha_s = d_s * (1 + tau/(eps+sigma_s))^p, tau=|sigma_L-sigma_R|
//  - Reconstructs entire polynomial per cell (supplies spatial derivatives to CK)
// ====================================================================

static const int MAX_L = 5;   // max polynomial coefficients (M+1, M<=4)
static const int MAX_S = 5;   // max stencil size (2k+1, k<=2)

// Fast integer power
static inline double ipow_weno(double x, int n) {
    double r = 1.0;
    for (int i = 0; i < n; ++i) r *= x;
    return r;
}

// ====================================================================
//  Precomputed coefficient tables (generated by SymPy)
//  ReconC/L/R[l][j]: cell averages -> Legendre coefficients
//  Rlm[l][m]: oscillation indicator matrix
//  EvalL/R[d][l]: Legendre coefficients -> d-th derivative at eta=0/1
// ====================================================================

struct DumbserCoeffs {
    int M;            // polynomial degree
    int L;            // = M+1, number of Legendre coefficients
    int k;            // stencil half-width
    int nStencil;     // = 2k+1, stencil size
    double ReconC[MAX_L][MAX_S];   // central stencil reconstruction
    double ReconL[MAX_L][MAX_S];   // left stencil reconstruction
    double ReconR[MAX_L][MAX_S];   // right stencil reconstruction
    double Rlm[MAX_L][MAX_L];     // oscillation indicator matrix
    double EvalLeft[MAX_L][MAX_L]; // evaluation at eta=0
    double EvalRight[MAX_L][MAX_L];// evaluation at eta=1
};

static DumbserCoeffs buildCoeffs(int M) {
    DumbserCoeffs c{};
    c.M = M;
    c.L = M + 1;
    c.k = (M % 2 == 0) ? M / 2 : (M + 1) / 2;
    c.nStencil = 2 * c.k + 1;

    // Zero-initialize
    for (int i = 0; i < MAX_L; ++i) {
        for (int j = 0; j < MAX_S; ++j) {
            c.ReconC[i][j] = 0.0;
            c.ReconL[i][j] = 0.0;
            c.ReconR[i][j] = 0.0;
        }
        for (int j = 0; j < MAX_L; ++j) {
            c.Rlm[i][j] = 0.0;
            c.EvalLeft[i][j] = 0.0;
            c.EvalRight[i][j] = 0.0;
        }
    }

    switch (M) {
    case 1: {
        // M=1, k=1, stencil=3 cells, 2 Legendre coefficients
        // Central (offsets: -1, 0, 1)
        c.ReconC[0][0]= 0.0; c.ReconC[0][1]= 1.0; c.ReconC[0][2]= 0.0;
        c.ReconC[1][0]=-0.25; c.ReconC[1][1]= 0.0; c.ReconC[1][2]= 0.25;
        // Left (offsets: -2, -1, 0)
        c.ReconL[0][0]= 0.0; c.ReconL[0][1]= 0.0; c.ReconL[0][2]= 1.0;
        c.ReconL[1][0]=-0.2; c.ReconL[1][1]=-0.1; c.ReconL[1][2]= 0.3;
        // Right (offsets: 0, 1, 2)
        c.ReconR[0][0]= 1.0; c.ReconR[0][1]= 0.0; c.ReconR[0][2]= 0.0;
        c.ReconR[1][0]=-0.3; c.ReconR[1][1]= 0.1; c.ReconR[1][2]= 0.2;
        // Oscillation indicator
        c.Rlm[1][1] = 4.0;
        // Eval at eta=0
        c.EvalLeft[0][0]= 1.0; c.EvalLeft[0][1]=-1.0;
        c.EvalLeft[1][0]= 0.0; c.EvalLeft[1][1]= 2.0;
        // Eval at eta=1
        c.EvalRight[0][0]= 1.0; c.EvalRight[0][1]= 1.0;
        c.EvalRight[1][0]= 0.0; c.EvalRight[1][1]= 2.0;
        break;
    }
    case 2: {
        // M=2, k=1, stencil=3 cells, 3 Legendre coefficients
        // Central (offsets: -1, 0, 1)
        c.ReconC[0][0]= 0.0;                c.ReconC[0][1]= 1.0;                c.ReconC[0][2]= 0.0;
        c.ReconC[1][0]=-2.5000000000000000e-01; c.ReconC[1][1]= 0.0;                c.ReconC[1][2]= 2.5000000000000000e-01;
        c.ReconC[2][0]= 8.3333333333333329e-02; c.ReconC[2][1]=-1.6666666666666666e-01; c.ReconC[2][2]= 8.3333333333333329e-02;
        // Left (offsets: -2, -1, 0)
        c.ReconL[0][0]= 0.0;                c.ReconL[0][1]= 0.0;                c.ReconL[0][2]= 1.0;
        c.ReconL[1][0]= 2.5000000000000000e-01; c.ReconL[1][1]=-1.0;                c.ReconL[1][2]= 7.5000000000000000e-01;
        c.ReconL[2][0]= 8.3333333333333329e-02; c.ReconL[2][1]=-1.6666666666666666e-01; c.ReconL[2][2]= 8.3333333333333329e-02;
        // Right (offsets: 0, 1, 2)
        c.ReconR[0][0]= 1.0;                c.ReconR[0][1]= 0.0;                c.ReconR[0][2]= 0.0;
        c.ReconR[1][0]=-7.5000000000000000e-01; c.ReconR[1][1]= 1.0;                c.ReconR[1][2]=-2.5000000000000000e-01;
        c.ReconR[2][0]= 8.3333333333333329e-02; c.ReconR[2][1]=-1.6666666666666666e-01; c.ReconR[2][2]= 8.3333333333333329e-02;
        // Oscillation indicator
        c.Rlm[1][1] = 4.0;
        c.Rlm[2][2] = 156.0;
        // Eval at eta=0
        c.EvalLeft[0][0]= 1.0; c.EvalLeft[0][1]=-1.0; c.EvalLeft[0][2]= 1.0;
        c.EvalLeft[1][0]= 0.0; c.EvalLeft[1][1]= 2.0; c.EvalLeft[1][2]=-6.0;
        c.EvalLeft[2][0]= 0.0; c.EvalLeft[2][1]= 0.0; c.EvalLeft[2][2]= 12.0;
        // Eval at eta=1
        c.EvalRight[0][0]= 1.0; c.EvalRight[0][1]= 1.0; c.EvalRight[0][2]= 1.0;
        c.EvalRight[1][0]= 0.0; c.EvalRight[1][1]= 2.0; c.EvalRight[1][2]= 6.0;
        c.EvalRight[2][0]= 0.0; c.EvalRight[2][1]= 0.0; c.EvalRight[2][2]= 12.0;
        break;
    }
    case 3: {
        // M=3, k=2, stencil=5 cells, 4 Legendre coefficients
        // Central (offsets: -2,-1,0,1,2)
        c.ReconC[0][0]= 0.0; c.ReconC[0][1]= 0.0; c.ReconC[0][2]= 1.0; c.ReconC[0][3]= 0.0; c.ReconC[0][4]= 0.0;
        c.ReconC[1][0]= 4.5833333333333330e-02; c.ReconC[1][1]=-3.4166666666666667e-01; c.ReconC[1][2]= 0.0; c.ReconC[1][3]= 3.4166666666666667e-01; c.ReconC[1][4]=-4.5833333333333330e-02;
        c.ReconC[2][0]= 1.9607843137254902e-02; c.ReconC[2][1]= 4.9019607843137254e-03; c.ReconC[2][2]=-4.9019607843137254e-02; c.ReconC[2][3]= 4.9019607843137254e-03; c.ReconC[2][4]= 1.9607843137254902e-02;
        c.ReconC[3][0]=-4.1666666666666666e-03; c.ReconC[3][1]= 8.3333333333333332e-03; c.ReconC[3][2]= 0.0; c.ReconC[3][3]=-8.3333333333333332e-03; c.ReconC[3][4]= 4.1666666666666666e-03;
        // Left (offsets: -4,-3,-2,-1,0)
        c.ReconL[0][0]= 0.0; c.ReconL[0][1]= 0.0; c.ReconL[0][2]= 0.0; c.ReconL[0][3]= 0.0; c.ReconL[0][4]= 1.0;
        c.ReconL[1][0]=-1.5772946859903381e-01; c.ReconL[1][1]= 4.7258454106280195e-01; c.ReconL[1][2]=-2.2137681159420289e-01; c.ReconL[1][3]=-8.4408212560386475e-01; c.ReconL[1][4]= 7.5060386473429952e-01;
        c.ReconL[2][0]=-5.7971014492753624e-02; c.ReconL[2][1]= 1.4855072463768115e-01; c.ReconL[2][2]=-1.4492753623188406e-02; c.ReconL[2][3]=-1.8478260869565216e-01; c.ReconL[2][4]= 1.0869565217391304e-01;
        c.ReconL[3][0]=-4.1062801932367152e-03; c.ReconL[3][1]= 8.0917874396135257e-03; c.ReconL[3][2]= 3.6231884057971015e-04; c.ReconL[3][3]=-8.5748792270531407e-03; c.ReconL[3][4]= 4.2270531400966180e-03;
        // Right (offsets: 0,1,2,3,4)
        c.ReconR[0][0]= 1.0; c.ReconR[0][1]= 0.0; c.ReconR[0][2]= 0.0; c.ReconR[0][3]= 0.0; c.ReconR[0][4]= 0.0;
        c.ReconR[1][0]=-7.5060386473429952e-01; c.ReconR[1][1]= 8.4408212560386475e-01; c.ReconR[1][2]= 2.2137681159420289e-01; c.ReconR[1][3]=-4.7258454106280195e-01; c.ReconR[1][4]= 1.5772946859903381e-01;
        c.ReconR[2][0]= 1.0869565217391304e-01; c.ReconR[2][1]=-1.8478260869565216e-01; c.ReconR[2][2]=-1.4492753623188406e-02; c.ReconR[2][3]= 1.4855072463768115e-01; c.ReconR[2][4]=-5.7971014492753624e-02;
        c.ReconR[3][0]=-4.2270531400966180e-03; c.ReconR[3][1]= 8.5748792270531407e-03; c.ReconR[3][2]=-3.6231884057971015e-04; c.ReconR[3][3]=-8.0917874396135257e-03; c.ReconR[3][4]= 4.1062801932367152e-03;
        // Oscillation indicator
        c.Rlm[1][1]= 4.0; c.Rlm[1][3]= 4.0;
        c.Rlm[2][2]= 156.0;
        c.Rlm[3][1]= 4.0; c.Rlm[3][3]= 15624.0;
        // Eval at eta=0
        c.EvalLeft[0][0]= 1.0; c.EvalLeft[0][1]=-1.0; c.EvalLeft[0][2]= 1.0; c.EvalLeft[0][3]=-1.0;
        c.EvalLeft[1][0]= 0.0; c.EvalLeft[1][1]= 2.0; c.EvalLeft[1][2]=-6.0; c.EvalLeft[1][3]= 12.0;
        c.EvalLeft[2][0]= 0.0; c.EvalLeft[2][1]= 0.0; c.EvalLeft[2][2]= 12.0; c.EvalLeft[2][3]=-60.0;
        c.EvalLeft[3][0]= 0.0; c.EvalLeft[3][1]= 0.0; c.EvalLeft[3][2]= 0.0; c.EvalLeft[3][3]= 120.0;
        // Eval at eta=1
        c.EvalRight[0][0]= 1.0; c.EvalRight[0][1]= 1.0; c.EvalRight[0][2]= 1.0; c.EvalRight[0][3]= 1.0;
        c.EvalRight[1][0]= 0.0; c.EvalRight[1][1]= 2.0; c.EvalRight[1][2]= 6.0; c.EvalRight[1][3]= 12.0;
        c.EvalRight[2][0]= 0.0; c.EvalRight[2][1]= 0.0; c.EvalRight[2][2]= 12.0; c.EvalRight[2][3]= 60.0;
        c.EvalRight[3][0]= 0.0; c.EvalRight[3][1]= 0.0; c.EvalRight[3][2]= 0.0; c.EvalRight[3][3]= 120.0;
        break;
    }
    case 4: {
        // M=4, k=2, stencil=5 cells, 5 Legendre coefficients
        // Central (offsets: -2,-1,0,1,2)
        c.ReconC[0][0]= 0.0; c.ReconC[0][1]= 0.0; c.ReconC[0][2]= 1.0; c.ReconC[0][3]= 0.0; c.ReconC[0][4]= 0.0;
        c.ReconC[1][0]= 4.5833333333333330e-02; c.ReconC[1][1]=-3.4166666666666667e-01; c.ReconC[1][2]= 0.0; c.ReconC[1][3]= 3.4166666666666667e-01; c.ReconC[1][4]=-4.5833333333333330e-02;
        c.ReconC[2][0]=-8.9285714285714281e-03; c.ReconC[2][1]= 1.1904761904761904e-01; c.ReconC[2][2]=-2.2023809523809523e-01; c.ReconC[2][3]= 1.1904761904761904e-01; c.ReconC[2][4]=-8.9285714285714281e-03;
        c.ReconC[3][0]=-4.1666666666666666e-03; c.ReconC[3][1]= 8.3333333333333332e-03; c.ReconC[3][2]= 0.0; c.ReconC[3][3]=-8.3333333333333332e-03; c.ReconC[3][4]= 4.1666666666666666e-03;
        c.ReconC[4][0]= 5.9523809523809529e-04; c.ReconC[4][1]=-2.3809523809523812e-03; c.ReconC[4][2]= 3.5714285714285713e-03; c.ReconC[4][3]=-2.3809523809523812e-03; c.ReconC[4][4]= 5.9523809523809529e-04;
        // Left (offsets: -4,-3,-2,-1,0)
        c.ReconL[0][0]= 0.0; c.ReconL[0][1]= 0.0; c.ReconL[0][2]= 0.0; c.ReconL[0][3]= 0.0; c.ReconL[0][4]= 1.0;
        c.ReconL[1][0]= 1.1250000000000000e-01; c.ReconL[1][1]=-6.0833333333333328e-01; c.ReconL[1][2]= 1.4000000000000000e+00; c.ReconL[1][3]=-1.9250000000000000e+00; c.ReconL[1][4]= 1.0208333333333333e+00;
        c.ReconL[2][0]= 7.4404761904761904e-02; c.ReconL[2][1]=-3.8095238095238093e-01; c.ReconL[2][2]= 7.7976190476190477e-01; c.ReconL[2][3]=-7.1428571428571430e-01; c.ReconL[2][4]= 2.4107142857142858e-01;
        c.ReconL[3][0]= 1.2500000000000001e-02; c.ReconL[3][1]=-5.8333333333333334e-02; c.ReconL[3][2]= 1.0000000000000001e-01; c.ReconL[3][3]=-7.4999999999999997e-02; c.ReconL[3][4]= 2.0833333333333332e-02;
        c.ReconL[4][0]= 5.9523809523809529e-04; c.ReconL[4][1]=-2.3809523809523812e-03; c.ReconL[4][2]= 3.5714285714285713e-03; c.ReconL[4][3]=-2.3809523809523812e-03; c.ReconL[4][4]= 5.9523809523809529e-04;
        // Right (offsets: 0,1,2,3,4)
        c.ReconR[0][0]= 1.0; c.ReconR[0][1]= 0.0; c.ReconR[0][2]= 0.0; c.ReconR[0][3]= 0.0; c.ReconR[0][4]= 0.0;
        c.ReconR[1][0]=-1.0208333333333333e+00; c.ReconR[1][1]= 1.9250000000000000e+00; c.ReconR[1][2]=-1.4000000000000000e+00; c.ReconR[1][3]= 6.0833333333333328e-01; c.ReconR[1][4]=-1.1250000000000000e-01;
        c.ReconR[2][0]= 2.4107142857142858e-01; c.ReconR[2][1]=-7.1428571428571430e-01; c.ReconR[2][2]= 7.7976190476190477e-01; c.ReconR[2][3]=-3.8095238095238093e-01; c.ReconR[2][4]= 7.4404761904761904e-02;
        c.ReconR[3][0]=-2.0833333333333332e-02; c.ReconR[3][1]= 7.4999999999999997e-02; c.ReconR[3][2]=-1.0000000000000001e-01; c.ReconR[3][3]= 5.8333333333333334e-02; c.ReconR[3][4]=-1.2500000000000001e-02;
        c.ReconR[4][0]= 5.9523809523809529e-04; c.ReconR[4][1]=-2.3809523809523812e-03; c.ReconR[4][2]= 3.5714285714285713e-03; c.ReconR[4][3]=-2.3809523809523812e-03; c.ReconR[4][4]= 5.9523809523809529e-04;
        // Oscillation indicator
        c.Rlm[1][1]= 4.0; c.Rlm[1][3]= 4.0;
        c.Rlm[2][2]= 156.0; c.Rlm[2][4]= 492.0;
        c.Rlm[3][1]= 4.0; c.Rlm[3][3]= 15624.0;
        c.Rlm[4][2]= 492.0; c.Rlm[4][4]= 3063160.0;
        // Eval at eta=0
        c.EvalLeft[0][0]= 1.0; c.EvalLeft[0][1]=-1.0; c.EvalLeft[0][2]= 1.0; c.EvalLeft[0][3]=-1.0; c.EvalLeft[0][4]= 1.0;
        c.EvalLeft[1][0]= 0.0; c.EvalLeft[1][1]= 2.0; c.EvalLeft[1][2]=-6.0; c.EvalLeft[1][3]= 12.0; c.EvalLeft[1][4]=-20.0;
        c.EvalLeft[2][0]= 0.0; c.EvalLeft[2][1]= 0.0; c.EvalLeft[2][2]= 12.0; c.EvalLeft[2][3]=-60.0; c.EvalLeft[2][4]= 180.0;
        c.EvalLeft[3][0]= 0.0; c.EvalLeft[3][1]= 0.0; c.EvalLeft[3][2]= 0.0; c.EvalLeft[3][3]= 120.0; c.EvalLeft[3][4]=-840.0;
        c.EvalLeft[4][0]= 0.0; c.EvalLeft[4][1]= 0.0; c.EvalLeft[4][2]= 0.0; c.EvalLeft[4][3]= 0.0; c.EvalLeft[4][4]= 1680.0;
        // Eval at eta=1
        c.EvalRight[0][0]= 1.0; c.EvalRight[0][1]= 1.0; c.EvalRight[0][2]= 1.0; c.EvalRight[0][3]= 1.0; c.EvalRight[0][4]= 1.0;
        c.EvalRight[1][0]= 0.0; c.EvalRight[1][1]= 2.0; c.EvalRight[1][2]= 6.0; c.EvalRight[1][3]= 12.0; c.EvalRight[1][4]= 20.0;
        c.EvalRight[2][0]= 0.0; c.EvalRight[2][1]= 0.0; c.EvalRight[2][2]= 12.0; c.EvalRight[2][3]= 60.0; c.EvalRight[2][4]= 180.0;
        c.EvalRight[3][0]= 0.0; c.EvalRight[3][1]= 0.0; c.EvalRight[3][2]= 0.0; c.EvalRight[3][3]= 120.0; c.EvalRight[3][4]= 840.0;
        c.EvalRight[4][0]= 0.0; c.EvalRight[4][1]= 0.0; c.EvalRight[4][2]= 0.0; c.EvalRight[4][3]= 0.0; c.EvalRight[4][4]= 1680.0;
        break;
    }
    default:
        break;
    }
    return c;
}

// ====================================================================
//  Core per-cell reconstruction: cell averages -> Legendre coefficients
// ====================================================================

// Compute oscillation indicator for a set of Legendre coefficients
// sigma = R_{lm} * w_l * w_m  (equation 18 of Dumbser 2008)
static double oscillation_indicator(const double wh[], int L, const double Rlm[][MAX_L]) {
    double sigma = 0.0;
    for (int l = 0; l < L; ++l) {
        for (int m = 0; m < L; ++m) {
            sigma += Rlm[l][m] * wh[l] * wh[m];
        }
    }
    return sigma;
}

// Reconstruct Legendre coefficients for one cell, one scalar variable
// u_stencil[0..nStencil-1] = cell averages on the stencil (centered on this cell)
// Output: wh[0..L-1] = WENO-combined Legendre coefficients
static void reconstruct_cell_legendre(
    const double u_center[],    // cell averages for central stencil [nS]
    const double u_left[],      // cell averages for left stencil [nS]
    const double u_right[],     // cell averages for right stencil [nS]
    double wh[],                // output: Legendre coefficients [L]
    const DumbserCoeffs& co,
    double epsilon, int r_power)
{
    const int L = co.L;
    const int nS = co.nStencil;

    // Step 1: Reconstruct on each stencil
    double wh_C[MAX_L] = {}, wh_L[MAX_L] = {}, wh_R[MAX_L] = {};
    for (int l = 0; l < L; ++l) {
        double vc = 0.0, vl = 0.0, vr = 0.0;
        for (int j = 0; j < nS; ++j) {
            vc += co.ReconC[l][j] * u_center[j];
            vl += co.ReconL[l][j] * u_left[j];
            vr += co.ReconR[l][j] * u_right[j];
        }
        wh_C[l] = vc;
        wh_L[l] = vl;
        wh_R[l] = vr;
    }

    // Step 2: Oscillation indicators for each stencil
    double sigma_C = oscillation_indicator(wh_C, L, co.Rlm);
    double sigma_L = oscillation_indicator(wh_L, L, co.Rlm);
    double sigma_R = oscillation_indicator(wh_R, L, co.Rlm);

    // Step 3: WENO-JS weights (Jiang, Shu, JCP 1996)
    //   alpha_s = lambda_s / (epsilon + sigma_s)^r
    const double lambda_C = 1.0e14;
    const double lambda_L = 1.0;
    const double lambda_R = 1.0;

    double alpha_C = lambda_C / std::pow(epsilon + sigma_C, r_power);
    double alpha_L = lambda_L / std::pow(epsilon + sigma_L, r_power);
    double alpha_R = lambda_R / std::pow(epsilon + sigma_R, r_power);

    double alpha_sum = alpha_C + alpha_L + alpha_R;
    double omega_C = alpha_C / alpha_sum;
    double omega_L = alpha_L / alpha_sum;
    double omega_R = alpha_R / alpha_sum;

    // Step 4: WENO-combined Legendre coefficients
    for (int l = 0; l < L; ++l) {
        wh[l] = omega_C * wh_C[l] + omega_L * wh_L[l] + omega_R * wh_R[l];
    }
}

// Evaluate interface derivatives from Legendre coefficients
// derivs[d] = (d^d/d_eta^d) w(eta_boundary) = sum_l Eval[d][l] * wh[l]
// Then convert to physical: Q_phys^(d) = derivs[d] / dx^d
static void eval_at_boundary(
    const double wh[], int L,
    const double Eval[][MAX_L],
    double derivs[],  // output: physical derivatives
    double inv_dx)
{
    double inv_dx_pow = 1.0;
    for (int d = 0; d < L; ++d) {
        double val = 0.0;
        for (int l = 0; l < L; ++l) {
            val += Eval[d][l] * wh[l];
        }
        derivs[d] = val * inv_dx_pow;
        inv_dx_pow *= inv_dx;
    }
}


// ====================================================================
//  Zhang-Shu positivity-preserving limiter
//  (Zhang & Shu, JCP 2010; "On positivity-preserving high order
//   discontinuous Galerkin schemes for compressible Euler equations")
//
//  Applied AFTER reconstruction, BEFORE boundary evaluation.
//  Modifies Legendre coefficients in-place to ensure:
//    (1) rho > 0   at all Gauss-Lobatto quadrature points in the cell
//    (2) p   > 0   at all Gauss-Lobatto quadrature points in the cell
//  Cell averages (wh[v][0]) are preserved exactly.
// ====================================================================

// Evaluate shifted Legendre polynomial P_l(xi) on [0,1] via recurrence
// P_0(xi) = 1,  P_1(xi) = 2*xi - 1,
// (n+1)*P_{n+1} = (2n+1)*(2*xi-1)*P_n - n*P_{n-1}
static double eval_shifted_legendre(int l, double xi) {
    if (l == 0) return 1.0;
    const double t = 2.0 * xi - 1.0;      // map [0,1] -> [-1,1]
    if (l == 1) return t;
    double Pnm1 = 1.0, Pn = t;
    for (int n = 1; n < l; ++n) {
        double Pnp1 = ((2*n + 1) * t * Pn - n * Pnm1) / (n + 1);
        Pnm1 = Pn;
        Pn   = Pnp1;
    }
    return Pn;
}

// Evaluate cell polynomial u(xi) = sum_{l=0}^{L-1} wh[l] * P_l(xi)
static double eval_cell_polynomial(const double wh[], int L, double xi) {
    double val = 0.0;
    for (int l = 0; l < L; ++l)
        val += wh[l] * eval_shifted_legendre(l, xi);
    return val;
}

// Gauss-Lobatto quadrature points on [0,1] for checking positivity.
// For polynomial degree M, we use M+2 GL points (endpoints + M interior).
static const int MAX_GL = 7;
struct GLPoints { int n; double xi[MAX_GL]; };

static GLPoints get_gauss_lobatto_points(int M) {
    GLPoints gl{};
    switch (M) {
    case 1:
        gl.n = 3;
        gl.xi[0] = 0.0;  gl.xi[1] = 0.5;  gl.xi[2] = 1.0;
        break;
    case 2:
        gl.n = 4;
        gl.xi[0] = 0.0;
        gl.xi[1] = 0.27639320225002103;   // (5-sqrt(5))/10
        gl.xi[2] = 0.72360679774997897;   // (5+sqrt(5))/10
        gl.xi[3] = 1.0;
        break;
    case 3:
        gl.n = 5;
        gl.xi[0] = 0.0;
        gl.xi[1] = 0.17267316464601141;   // (1-sqrt(3/7))/2
        gl.xi[2] = 0.5;
        gl.xi[3] = 0.82732683535398859;   // (1+sqrt(3/7))/2
        gl.xi[4] = 1.0;
        break;
    case 4:
        gl.n = 6;
        gl.xi[0] = 0.0;
        gl.xi[1] = 0.11747233803526763;   // GL6 interior nodes on [0,1]
        gl.xi[2] = 0.35738424175967748;
        gl.xi[3] = 0.64261575824032252;
        gl.xi[4] = 0.88252766196473237;
        gl.xi[5] = 1.0;
        break;
    default:  // M=0 or fallback: just check endpoints
        gl.n = 2;
        gl.xi[0] = 0.0;  gl.xi[1] = 1.0;
        break;
    }
    return gl;
}

// Zhang-Shu positivity-preserving limiter for one cell.
//   wh[3][MAX_L]: Legendre coefficients for (rho, m, E)
//   L:            number of Legendre coefficients (= M+1)
//   M:            polynomial degree
//
// After limiting, wh[v][0] (cell averages) are unchanged,
// and the polynomial satisfies rho > 0, p > 0 at all GL points.
static void zhang_shu_limiter(double wh[3][MAX_L], int L, int M) {
    const double rho_bar = wh[0][0];   // cell-average density
    const double m_bar   = wh[1][0];   // cell-average momentum
    const double E_bar   = wh[2][0];   // cell-average energy
    const double gm1     = Gamma - 1.0;

    // Pressure of cell average
    const double p_bar = gm1 * (E_bar - 0.5 * m_bar * m_bar / rho_bar);

    // If cell average itself is unphysical, flatten to piecewise constant
    if (rho_bar <= 0.0 || p_bar <= 0.0 ||
        !std::isfinite(rho_bar) || !std::isfinite(p_bar)) {
        for (int v = 0; v < 3; ++v)
            for (int l = 1; l < L; ++l)
                wh[v][l] = 0.0;
        return;
    }

    // Small positive floor: min(1e-13, cell_average)
    const double eps_rho = std::min(1.0e-13, rho_bar);
    const double eps_p   = std::min(1.0e-13, p_bar);

    // Nothing to limit for piecewise constant
    if (L <= 1) return;

    // Gauss-Lobatto evaluation points
    static const GLPoints gl1 = get_gauss_lobatto_points(1);
    static const GLPoints gl2 = get_gauss_lobatto_points(2);
    static const GLPoints gl3 = get_gauss_lobatto_points(3);
    static const GLPoints gl4 = get_gauss_lobatto_points(4);
    const GLPoints* gl = nullptr;
    switch (M) {
        case 1: gl = &gl1; break;
        case 2: gl = &gl2; break;
        case 3: gl = &gl3; break;
        case 4: gl = &gl4; break;
        default: gl = &gl1; break;
    }
    const int nGL = gl->n;

    // ----------------------------------------------------------------
    // Step 1: Density limiter
    //   Find min rho at GL points. If RhoMin < eps_rho, scale
    //   ALL higher-order coefficients by theta1 so that
    //   rho_limited(xi) = theta1*(rho(xi) - rho_bar) + rho_bar >= eps_rho.
    // ----------------------------------------------------------------
    double RhoMin = rho_bar;
    for (int q = 0; q < nGL; ++q) {
        double rho_q = eval_cell_polynomial(wh[0], L, gl->xi[q]);
        if (rho_q < RhoMin) RhoMin = rho_q;
    }

    if (RhoMin < eps_rho) {
        double theta1 = (rho_bar - eps_rho) / (rho_bar - RhoMin);
        if (theta1 < 0.0) theta1 = 0.0;
        if (theta1 > 1.0) theta1 = 1.0;
        // Scale ALL variables' higher-order coefficients by theta1
        for (int v = 0; v < 3; ++v)
            for (int l = 1; l < L; ++l)
                wh[v][l] *= theta1;
    }

    // ----------------------------------------------------------------
    // Step 2: Pressure limiter
    //   After density limiting, check pressure at GL points.
    //   If p < eps_p at any point, find theta2 via bisection such that
    //   blending toward cell average restores p >= eps_p.
    // ----------------------------------------------------------------
    double theta2 = 1.0;

    for (int q = 0; q < nGL; ++q) {
        double rho_q = eval_cell_polynomial(wh[0], L, gl->xi[q]);
        double m_q   = eval_cell_polynomial(wh[1], L, gl->xi[q]);
        double E_q   = eval_cell_polynomial(wh[2], L, gl->xi[q]);
        double p_q   = gm1 * (E_q - 0.5 * m_q * m_q / rho_q);

        if (p_q < eps_p) {
            // Bisect for theta in [0, 1]:
            //   U(theta) = theta * (U_q - U_bar) + U_bar
            //   p(theta) = (g-1)*(E(theta) - m(theta)^2/(2*rho(theta)))
            // At theta=0: p = p_bar > 0.  At theta=1: p = p_q < eps_p.
            double lo = 0.0, hi = 1.0;
            for (int iter = 0; iter < 50; ++iter) {
                double mid = 0.5 * (lo + hi);
                double r = mid * (rho_q - rho_bar) + rho_bar;
                double m = mid * (m_q   - m_bar)   + m_bar;
                double e = mid * (E_q   - E_bar)   + E_bar;
                double p = gm1 * (e - 0.5 * m * m / r);
                if (p < eps_p)
                    hi = mid;
                else
                    lo = mid;
            }
            if (lo < theta2) theta2 = lo;
        }
    }

    if (theta2 < 1.0) {
        for (int v = 0; v < 3; ++v)
            for (int l = 1; l < L; ++l)
                wh[v][l] *= theta2;
    }
}


// ====================================================================
//  WENO1d public API (same interface as before)
// ====================================================================

WENO1d::WENO1d(int Polydegree, double dx, double epsilon, int qPower)
    : m_dx(dx), m_M(Polydegree), m_epsilon(epsilon), m_qPower(qPower)
{
    m_TotalStencilsize = 2 * m_M + 1;
    m_PolyStencilsize  = m_M + 1;

    if (m_dx <= 0.0) {
        std::cerr << "[WENO] dx must be positive.\n";
        std::exit(EXIT_FAILURE);
    }

    if (m_M < 0 || m_M > 4) {
        std::cerr << "[WENO] Implemented for degree M=0,1,2,3,4 only.\n";
        std::exit(EXIT_FAILURE);
    }

    // WENO-DK multiplicative formula: p controls shock dissipation per order.
    // M=3 (ADER4): p=3  -> more dissipation, less oscillatory near shocks
    // M=4 (ADER5): p=2  -> standard WENO-Z, slightly less dissipation
    // This ensures ADER4 oscillates less than ADER5 at discontinuities,
    // while both retain their formal convergence orders on smooth problems.
    if (m_epsilon > 1e-10) m_epsilon = 1e-14;
    // Per-order r_power: higher = more dissipative near shocks
    // Gives ADER3 < ADER4 < ADER5 oscillation ordering
    if      (m_M == 2) m_qPower = 4;
    else if (m_M == 3) m_qPower = 3;
    else               m_qPower = 2;

    // Legacy arrays (unused in new implementation but kept for header compat)
    m_CMatsL.resize(1);
    m_CMatsR.resize(1);
    m_BMats.resize(1);
    m_optWeightsL.assign(1, 0.0);
    m_optWeightsR.assign(1, 0.0);
}

void WENO1d::reconstruct_for_flux(
    const VectOfVectDouble& Ubc,
    int i_interface,
    VectOfVectDouble& U_WenoL,
    VectOfVectDouble& U_WenoR,
    int Nghost
) const {
    const int nVars = (int)Ubc[0].size();

    U_WenoL.assign(m_M + 1, VectOfDouble(nVars, 0.0));
    U_WenoR.assign(m_M + 1, VectOfDouble(nVars, 0.0));

    if (m_M == 0) {
        U_WenoL[0] = Ubc[i_interface + Nghost - 1];
        U_WenoR[0] = Ubc[i_interface + Nghost];
        return;
    }

    static const DumbserCoeffs coeff1 = buildCoeffs(1);
    static const DumbserCoeffs coeff2 = buildCoeffs(2);
    static const DumbserCoeffs coeff3 = buildCoeffs(3);
    static const DumbserCoeffs coeff4 = buildCoeffs(4);

    const DumbserCoeffs* co = nullptr;
    switch (m_M) {
        case 1: co = &coeff1; break;
        case 2: co = &coeff2; break;
        case 3: co = &coeff3; break;
        case 4: co = &coeff4; break;
    }

    const int L = co->L;
    const int k = co->k;
    const int nS = co->nStencil;
    const double inv_dx = 1.0 / m_dx;

    // Left cell of interface: ghost-padded index = i_interface + Nghost - 1
    // Right cell of interface: ghost-padded index = i_interface + Nghost
    const int iL_cell = i_interface + Nghost - 1;  // left cell
    const int iR_cell = i_interface + Nghost;       // right cell

    // --- Reconstruct LEFT cell: all variables first, then limit, then eval ---
    double wh_left[3][MAX_L];
    for (int v = 0; v < nVars; ++v) {
        double u_center_L[MAX_S], u_left_L[MAX_S], u_right_L[MAX_S];
        for (int j = 0; j < nS; ++j) {
            u_center_L[j] = Ubc[iL_cell - k + j][v];   // central: iL-k .. iL+k
            u_left_L[j]   = Ubc[iL_cell - 2*k + j][v];  // left:    iL-2k .. iL
            u_right_L[j]  = Ubc[iL_cell + j][v];         // right:   iL .. iL+2k
        }
        reconstruct_cell_legendre(u_center_L, u_left_L, u_right_L, wh_left[v],
                                  *co, m_epsilon, m_qPower);
    }

    // Zhang-Shu positivity limiter on left cell
    zhang_shu_limiter(wh_left, L, m_M);

    // Evaluate at right boundary (eta=1) of left cell
    for (int v = 0; v < nVars; ++v) {
        double derivs_L[MAX_L];
        eval_at_boundary(wh_left[v], L, co->EvalRight, derivs_L, inv_dx);
        for (int d = 0; d < L; ++d)
            U_WenoL[d][v] = derivs_L[d];
    }

    // --- Reconstruct RIGHT cell: all variables first, then limit, then eval ---
    double wh_right[3][MAX_L];
    for (int v = 0; v < nVars; ++v) {
        double u_center_R[MAX_S], u_left_R[MAX_S], u_right_R[MAX_S];
        for (int j = 0; j < nS; ++j) {
            u_center_R[j] = Ubc[iR_cell - k + j][v];
            u_left_R[j]   = Ubc[iR_cell - 2*k + j][v];
            u_right_R[j]  = Ubc[iR_cell + j][v];
        }
        reconstruct_cell_legendre(u_center_R, u_left_R, u_right_R, wh_right[v],
                                  *co, m_epsilon, m_qPower);
    }

    // Zhang-Shu positivity limiter on right cell
    zhang_shu_limiter(wh_right, L, m_M);

    // Evaluate at left boundary (eta=0) of right cell
    for (int v = 0; v < nVars; ++v) {
        double derivs_R[MAX_L];
        eval_at_boundary(wh_right[v], L, co->EvalLeft, derivs_R, inv_dx);
        for (int d = 0; d < L; ++d)
            U_WenoR[d][v] = derivs_R[d];
    }
}


// ====================================================================
//  reconstruct_all_interfaces (allocating version)
// ====================================================================

void WENO1d::reconstruct_all_interfaces(
    const std::vector<Conserved>& U,
    std::vector<InterfacePoly>& PolyL,
    std::vector<InterfacePoly>& PolyR,
    WenoBCType bc
) const {
    const int nx = (int)U.size();
    const int Nghost = requiredGhost();

    std::vector<Conserved> Ubc_cons =
        (bc == WenoBCType::Periodic) ? make_periodic_Ubc(U, Nghost)
                                     : make_outflow_Ubc(U, Nghost);

    VectOfVectDouble Ubc = conserved_to_matrix(Ubc_cons);

    PolyL.assign(nx, InterfacePoly{});
    PolyR.assign(nx, InterfacePoly{});

    #pragma omp parallel for schedule(static)
    for (int i_interface = 0; i_interface < nx; ++i_interface) {
        VectOfVectDouble WL, WR;
        reconstruct_for_flux(Ubc, i_interface, WL, WR, Nghost);

        InterfacePoly left{}, right{};

        left.Q   = Conserved{WL[0][0], WL[0][1], WL[0][2]};
        right.Q  = Conserved{WR[0][0], WR[0][1], WR[0][2]};

        if (m_M >= 1) {
            left.Qx  = Conserved{WL[1][0], WL[1][1], WL[1][2]};
            right.Qx = Conserved{WR[1][0], WR[1][1], WR[1][2]};
        }
        if (m_M >= 2) {
            left.Qxx  = Conserved{WL[2][0], WL[2][1], WL[2][2]};
            right.Qxx = Conserved{WR[2][0], WR[2][1], WR[2][2]};
        }
        if (m_M >= 3) {
            left.Qxxx  = Conserved{WL[3][0], WL[3][1], WL[3][2]};
            right.Qxxx = Conserved{WR[3][0], WR[3][1], WR[3][2]};
        }
        if (m_M >= 4) {
            left.Qxxxx  = Conserved{WL[4][0], WL[4][1], WL[4][2]};
            right.Qxxxx = Conserved{WR[4][0], WR[4][1], WR[4][2]};
        }

        // Positivity-preserving fallback (allocating version)
        auto is_physical = [](const Conserved& Q) -> bool {
            if (Q.rho <= 0.0 || !std::isfinite(Q.rho)) return false;
            double p = (Gamma - 1.0) * (Q.E - 0.5 * Q.mom * Q.mom / Q.rho);
            return p > 0.0 && std::isfinite(p);
        };

        if (!is_physical(left.Q)) {
            int iL_ghost = i_interface + Nghost - 1;
            left.Q = Conserved{Ubc[iL_ghost][0], Ubc[iL_ghost][1], Ubc[iL_ghost][2]};
            left.Qx = left.Qxx = left.Qxxx = left.Qxxxx = Conserved{0,0,0};
        }

        if (!is_physical(right.Q)) {
            int iR_ghost = i_interface + Nghost;
            right.Q = Conserved{Ubc[iR_ghost][0], Ubc[iR_ghost][1], Ubc[iR_ghost][2]};
            right.Qx = right.Qxx = right.Qxxx = right.Qxxxx = Conserved{0,0,0};
        }

        PolyL[i_interface] = left;
        PolyR[i_interface] = right;
    }
}


// ====================================================================
//  helpers (same as before)
// ====================================================================

std::vector<Conserved> WENO1d::make_outflow_Ubc(const std::vector<Conserved>& U, int Nghost) {
    const int nx = (int)U.size();
    std::vector<Conserved> Ubc(nx + 2 * Nghost);

    for (int g = 0; g < Nghost; ++g) Ubc[g] = U[0];
    for (int i = 0; i < nx; ++i)    Ubc[Nghost + i] = U[i];
    for (int g = 0; g < Nghost; ++g) Ubc[Nghost + nx + g] = U[nx - 1];

    return Ubc;
}

std::vector<Conserved> WENO1d::make_periodic_Ubc(const std::vector<Conserved>& U, int Nghost) {
    const int nx = (int)U.size();
    std::vector<Conserved> Ubc(nx + 2 * Nghost);

    for (int i = 0; i < nx + 2 * Nghost; ++i) {
        int idx = (i - Nghost) % nx;
        if (idx < 0) idx += nx;
        Ubc[i] = U[idx];
    }
    return Ubc;
}

VectOfVectDouble WENO1d::conserved_to_matrix(const std::vector<Conserved>& U) {
    const int n = (int)U.size();
    VectOfVectDouble M(n, VectOfDouble(3, 0.0));
    for (int i = 0; i < n; ++i) {
        M[i][0] = U[i].rho;
        M[i][1] = U[i].mom;
        M[i][2] = U[i].E;
    }
    return M;
}

// ====================================================================
//  In-place / buffer-reuse methods
// ====================================================================

void WENO1d::fill_periodic_Ubc(const std::vector<Conserved>& U, int Nghost,
                                std::vector<Conserved>& Ubc)
{
    const int nx = (int)U.size();
    const int nTotal = nx + 2 * Nghost;
    if ((int)Ubc.size() != nTotal) Ubc.resize(nTotal);

    for (int i = 0; i < nTotal; ++i) {
        int idx = (i - Nghost) % nx;
        if (idx < 0) idx += nx;
        Ubc[i] = U[idx];
    }
}

void WENO1d::fill_outflow_Ubc(const std::vector<Conserved>& U, int Nghost,
                               std::vector<Conserved>& Ubc)
{
    const int nx = (int)U.size();
    const int nTotal = nx + 2 * Nghost;
    if ((int)Ubc.size() != nTotal) Ubc.resize(nTotal);

    for (int g = 0; g < Nghost; ++g) Ubc[g] = U[0];
    for (int i = 0; i < nx; ++i)    Ubc[Nghost + i] = U[i];
    for (int g = 0; g < Nghost; ++g) Ubc[Nghost + nx + g] = U[nx - 1];
}

void WENO1d::fill_matrix(const std::vector<Conserved>& Ubc,
                          VectOfVectDouble& mat)
{
    const int n = (int)Ubc.size();
    if ((int)mat.size() != n) {
        mat.assign(n, VectOfDouble(3, 0.0));
    }
    for (int i = 0; i < n; ++i) {
        mat[i][0] = Ubc[i].rho;
        mat[i][1] = Ubc[i].mom;
        mat[i][2] = Ubc[i].E;
    }
}

WENOWorkspace WENO1d::alloc_workspace(int nx) const {
    WENOWorkspace ws;
    const int Nghost = requiredGhost();
    const int nTotal = nx + 2 * Nghost;
    ws.Ubc_cons.resize(nTotal);
    ws.Ubc_mat.assign(nTotal, VectOfDouble(3, 0.0));
    ws.PolyL.resize(nx);
    ws.PolyR.resize(nx);
    return ws;
}

void WENO1d::reconstruct_all_interfaces(
    const std::vector<Conserved>& U,
    WenoBCType bc,
    WENOWorkspace& ws
) const {
    const int nx = (int)U.size();
    const int Nghost = requiredGhost();

    if (bc == WenoBCType::Periodic)
        fill_periodic_Ubc(U, Nghost, ws.Ubc_cons);
    else
        fill_outflow_Ubc(U, Nghost, ws.Ubc_cons);

    fill_matrix(ws.Ubc_cons, ws.Ubc_mat);

    if ((int)ws.PolyL.size() != nx) ws.PolyL.resize(nx);
    if ((int)ws.PolyR.size() != nx) ws.PolyR.resize(nx);

    #pragma omp parallel for schedule(static)
    for (int i_interface = 0; i_interface < nx; ++i_interface) {
        VectOfVectDouble WL, WR;
        reconstruct_for_flux(ws.Ubc_mat, i_interface, WL, WR, Nghost);

        InterfacePoly left{}, right{};

        left.Q   = Conserved{WL[0][0], WL[0][1], WL[0][2]};
        right.Q  = Conserved{WR[0][0], WR[0][1], WR[0][2]};

        if (m_M >= 1) {
            left.Qx  = Conserved{WL[1][0], WL[1][1], WL[1][2]};
            right.Qx = Conserved{WR[1][0], WR[1][1], WR[1][2]};
        }
        if (m_M >= 2) {
            left.Qxx  = Conserved{WL[2][0], WL[2][1], WL[2][2]};
            right.Qxx = Conserved{WR[2][0], WR[2][1], WR[2][2]};
        }
        if (m_M >= 3) {
            left.Qxxx  = Conserved{WL[3][0], WL[3][1], WL[3][2]};
            right.Qxxx = Conserved{WR[3][0], WR[3][1], WR[3][2]};
        }
        if (m_M >= 4) {
            left.Qxxxx  = Conserved{WL[4][0], WL[4][1], WL[4][2]};
            right.Qxxxx = Conserved{WR[4][0], WR[4][1], WR[4][2]};
        }

        // Positivity-preserving fallback: if reconstructed interface value
        // has negative density or negative pressure, fall back to cell average
        // (piecewise constant, zero derivatives). This prevents blowup near shocks.
        auto is_physical = [](const Conserved& Q) -> bool {
            if (Q.rho <= 0.0 || !std::isfinite(Q.rho)) return false;
            double p = (Gamma - 1.0) * (Q.E - 0.5 * Q.mom * Q.mom / Q.rho);
            return p > 0.0 && std::isfinite(p);
        };

        if (!is_physical(left.Q)) {
            // Fall back to cell average of left cell (index i_interface - 1)
            int iL_ghost = i_interface + Nghost - 1;
            left.Q = Conserved{ws.Ubc_mat[iL_ghost][0], ws.Ubc_mat[iL_ghost][1], ws.Ubc_mat[iL_ghost][2]};
            left.Qx = left.Qxx = left.Qxxx = left.Qxxxx = Conserved{0,0,0};
        }

        if (!is_physical(right.Q)) {
            // Fall back to cell average of right cell (index i_interface)
            int iR_ghost = i_interface + Nghost;
            right.Q = Conserved{ws.Ubc_mat[iR_ghost][0], ws.Ubc_mat[iR_ghost][1], ws.Ubc_mat[iR_ghost][2]};
            right.Qx = right.Qxx = right.Qxxx = right.Qxxxx = Conserved{0,0,0};
        }

        ws.PolyL[i_interface] = left;
        ws.PolyR[i_interface] = right;
    }
}

// Legacy methods (kept for API compatibility but unused in new algorithm)
void WENO1d::setCoefficients() { /* Dumbser coefficients are in buildCoeffs() */ }
void WENO1d::getStencil(const VectOfVectDouble&, int, VectOfVectDouble&, int) const {}
void WENO1d::reconstructAtInterface(const VectOfDouble&, const VectOfDouble&, VectOfDouble&, VectOfDouble&) const {}
void WENO1d::computeWeights(const VectOfDouble&, const VectOfDouble&, VectOfDouble&, VectOfDouble&) const {}